[2023-08-22T15:10:32.832+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_hdb_resale_data.branch_download_task manual__2023-08-22T15:10:28.806779+00:00 [queued]>
[2023-08-22T15:10:32.859+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_hdb_resale_data.branch_download_task manual__2023-08-22T15:10:28.806779+00:00 [queued]>
[2023-08-22T15:10:32.860+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-22T15:10:32.887+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): branch_download_task> on 2023-08-22 15:10:28.806779+00:00
[2023-08-22T15:10:32.903+0000] {standard_task_runner.py:57} INFO - Started process 2182 to run task
[2023-08-22T15:10:32.910+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'download_hdb_resale_data', 'branch_download_task', 'manual__2023-08-22T15:10:28.806779+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/download_house_price.py', '--cfg-path', '/tmp/tmp2hcfqpta']
[2023-08-22T15:10:32.913+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask branch_download_task
[2023-08-22T15:10:33.004+0000] {task_command.py:415} INFO - Running <TaskInstance: download_hdb_resale_data.branch_download_task manual__2023-08-22T15:10:28.806779+00:00 [running]> on host 86cb0f57e8f2
[2023-08-22T15:10:33.147+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_hdb_resale_data' AIRFLOW_CTX_TASK_ID='branch_download_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-22T15:10:28.806779+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-22T15:10:28.806779+00:00'
[2023-08-22T15:10:33.163+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_house_price.py", line 29, in check_last_dag_run_success
    if last_modified > datetime.now():
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
[2023-08-22T15:10:33.181+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_hdb_resale_data, task_id=branch_download_task, execution_date=20230822T151028, start_date=20230822T151032, end_date=20230822T151033
[2023-08-22T15:10:33.205+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task branch_download_task ('>' not supported between instances of 'str' and 'datetime.datetime'; 2182)
[2023-08-22T15:10:33.244+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-22T15:10:33.319+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
