[2023-08-22T14:56:04.804+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_hdb_resale_data.branch_download_task manual__2023-08-22T14:55:59.060690+00:00 [queued]>
[2023-08-22T14:56:04.831+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_hdb_resale_data.branch_download_task manual__2023-08-22T14:55:59.060690+00:00 [queued]>
[2023-08-22T14:56:04.832+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-22T14:56:04.867+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): branch_download_task> on 2023-08-22 14:55:59.060690+00:00
[2023-08-22T14:56:04.889+0000] {standard_task_runner.py:57} INFO - Started process 1683 to run task
[2023-08-22T14:56:04.894+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'download_hdb_resale_data', 'branch_download_task', 'manual__2023-08-22T14:55:59.060690+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/download_house_price.py', '--cfg-path', '/tmp/tmpp4jv9xk7']
[2023-08-22T14:56:04.895+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask branch_download_task
[2023-08-22T14:56:05.029+0000] {task_command.py:415} INFO - Running <TaskInstance: download_hdb_resale_data.branch_download_task manual__2023-08-22T14:55:59.060690+00:00 [running]> on host 86cb0f57e8f2
[2023-08-22T14:56:05.216+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_hdb_resale_data' AIRFLOW_CTX_TASK_ID='branch_download_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-22T14:55:59.060690+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-22T14:55:59.060690+00:00'
[2023-08-22T14:56:05.217+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 226, in execute
    branch = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_house_price.py", line 28, in check_last_dag_run_success
    if last_modified > datetime.now():
TypeError: '>' not supported between instances of 'str' and 'datetime.datetime'
[2023-08-22T14:56:05.239+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_hdb_resale_data, task_id=branch_download_task, execution_date=20230822T145559, start_date=20230822T145604, end_date=20230822T145605
[2023-08-22T14:56:05.267+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task branch_download_task ('>' not supported between instances of 'str' and 'datetime.datetime'; 1683)
[2023-08-22T14:56:05.311+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-22T14:56:05.393+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
