[2023-08-20T11:18:38.327+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_rocket_launches.get_picture_task manual__2023-08-20T11:18:36.968859+00:00 [queued]>
[2023-08-20T11:18:38.341+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_rocket_launches.get_picture_task manual__2023-08-20T11:18:36.968859+00:00 [queued]>
[2023-08-20T11:18:38.342+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-20T11:18:38.364+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): get_picture_task> on 2023-08-20 11:18:36.968859+00:00
[2023-08-20T11:18:38.377+0000] {standard_task_runner.py:57} INFO - Started process 2589 to run task
[2023-08-20T11:18:38.381+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'get_picture_task', 'manual__2023-08-20T11:18:36.968859+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/rocket_launch.py', '--cfg-path', '/tmp/tmppvvd6pk8']
[2023-08-20T11:18:38.383+0000] {standard_task_runner.py:85} INFO - Job 12: Subtask get_picture_task
[2023-08-20T11:18:38.466+0000] {task_command.py:415} INFO - Running <TaskInstance: download_rocket_launches.get_picture_task manual__2023-08-20T11:18:36.968859+00:00 [running]> on host 83683a92d346
[2023-08-20T11:18:38.592+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_rocket_launches' AIRFLOW_CTX_TASK_ID='get_picture_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-20T11:18:36.968859+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-20T11:18:36.968859+00:00'
[2023-08-20T11:18:38.594+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/rocket_launch.py", line 24, in get_pictures
    with open("/tmp/launches.json") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/launches.json'
[2023-08-20T11:18:38.611+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=get_picture_task, execution_date=20230820T111836, start_date=20230820T111838, end_date=20230820T111838
[2023-08-20T11:18:38.635+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task get_picture_task ([Errno 2] No such file or directory: '/tmp/launches.json'; 2589)
[2023-08-20T11:18:38.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-20T11:18:38.706+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
